include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.drift.dart"
    - "**/*.mocks.dart"
    - "**/injection.config.dart"
    - "**/*.gr.dart"