# se tuvo que configurar este archivo porque estaba ocurriendo este bug entre
# drift y mockito: sentry.io/organizations/shepherdator/issues/?project=5925032
# la solucion fue sacada de la documentacion de drift: 
# https://drift.simonbinder.eu/docs/advanced-features/builder_options/#using-drift-classes-in-other-builders
targets:
  $default:
    # disable the default generators, we'll only use the non-shared drift generator here
    auto_apply_builders: false
    builders:
      drift_dev|not_shared:
        enabled: true
        # If needed, you can configure the builder like this:
        # options:
        #   skip_verification_code: true
        #   use_experimental_inference: true
      # This builder is necessary for drift-file preprocessing. You can disable it if you're not
      # using .drift files with type converters.
      drift_dev|preparing_builder:
        enabled: true
  
  run_built_value:
    dependencies: ['mockito']
    builders:
      # Disable drift builders. By default, those would run on each target
      drift_dev:
        enabled: false
      drift_dev|preparing_builder:
        enabled: false
      # we don't need to disable drift_generator_not_shared, because it's disabled by default