name: inspecciones
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0-0 <3.0.0"
  flutter: ">=2.5.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^2.3.0
  collection: ^1.15.0
  cool_stepper: ^1.2.1
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  datetime_picker_formfield: ^2.0.0
  editable: ^2.0.0
  enum_to_string: ^2.0.1
  file: ^6.1.2
  flutter_archive: ^4.0.1
  flutter_bloc: ^7.2.0
  flutter_downloader: ^1.6.1
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  grouped_list: ^4.1.0
  image_picker: ^0.8.3+3
  injectable: ^1.5.0
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  moor: ^4.5.0
  moor_db_viewer: ^4.4.0
  open_file: ^3.2.1
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^6.0.0
  reactive_forms: ^10.6.2
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.7
  reactive_multi_image_picker:
    git:
      url: https://github.com/victorcatn/reactive_multi_image_picker.git
      ref: multi_platform_support
  rflutter_alert: ^2.0.4
  sentry_flutter: ^6.0.1
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  sqlite3_flutter_libs: ^0.5.0
  timeline_tile: ^2.0.0
  simple_tooltip: ^1.0.0
  url_launcher: ^6.0.9
  connectivity_plus: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.1
  auto_route_generator: ^2.3.0
  moor_generator: ^4.5.1
  flutter_launcher_icons: ^0.9.1
  freezed: ^0.14.5
  injectable_generator: ^1.5.0
  json_serializable: ^5.0.0 
  flutter_lints: ^1.0.4
  flutter_test: # tests
    sdk: flutter
  test: ^1.17.10
  mockito: ^5.0.15
  file_testing: ^3.0.0
  bloc_test: ^8.1.0
  

flutter_icons:
  image_path: "assets/images/logo-gomac.png"
  android: true # can specify file name here e.g. "ic_launcher"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-gomac.png
    - assets/images/logo-gomac-texto.png
    - assets/images/Posicion.jpeg

