name: inspecciones
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^2.2.0
  collection: ^1.15.0
  cool_stepper: ^1.2.1
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  datetime_picker_formfield: ^2.0.0
  dropdown_search: ^0.6.3
  editable: ^2.0.0
  enum_to_string: ^2.0.1
  flutter_archive: ^4.0.1
  flutter_bloc: ^7.1.0
  flutter_downloader: ^1.6.1
  freezed_annotation: ^0.14.2
  get_it: ^7.2.0
  grouped_list: ^4.1.0
  image_picker: ^0.8.3
  injectable: ^1.4.1
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  kt_dart: ^0.9.1
  moor: ^4.4.1
  moor_db_viewer: ^4.3.0
  multi_select_flutter: ^4.0.0
  open_file: ^3.2.1
  path: ^1.8.0
  path_provider: ^2.0.2
  pdf: ^3.4.2
  provider: ^5.0.0
  reactive_forms: ^10.6.0
  rflutter_alert: ^2.0.4
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  sqlite3_flutter_libs: ^0.5.0
  timeline_tile: ^2.0.0
  #simple_tooltip: ^0.1.16 #esperar a que suban la null safety
  url_launcher: ^6.0.9

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.1.0
  flutter_launcher_icons: ^0.9.1
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.4 #aumentar a 5.0.0 cuando moor_generator tenga el analyzer 2.0
  lint: ^1.5.3
  moor_generator: ^4.4.1

flutter_icons:
  image_path: "assets/images/logo-gomac.png"
  android: true # can specify file name here e.g. "ic_launcher"

dependency_overrides: null
#analyzer: '0.39.14'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo-gomac.png
    - assets/images/logo-gomac-texto.png
    - assets/images/Posicion.jpeg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
