name: inspecciones
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ">=2.14.0-0 <3.0.0"
  flutter: ">=2.8.1-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  enum_to_string: ^2.0.1
  file: ^6.1.2
  cross_file: ^0.3.2
  flutter_archive: ^4.1.0
  freezed_annotation: ^1.1.0
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.4.0
  drift: ^1.6.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.1
  moor_db_viewer: ^5.0.0
  android_path_provider: ^0.3.0
  reactive_forms: ^11.0.0
  hooks_riverpod: ^1.0.3
  reactive_multi_image_picker:
    git:
      url: https://github.com/victorcatn/reactive_multi_image_picker.git
      ref: multi_platform_support
  rflutter_alert: ^2.0.4
  sentry_flutter: ^6.2.2
  shared_preferences: ^2.0.11
  simple_tooltip: ^1.0.0
  url_launcher: ^6.0.17
  go_router: ^2.5.7
  connectivity_plus: ^2.2.0
  
  uuid: ^3.0.5
  rxdart: ^0.27.3
  diacritic: ^0.1.3
  horizontal_data_table: ^3.6.1+1

dev_dependencies:
  drift_dev: ^1.6.0
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  flutter_lints: ^1.0.4
  test: ^1.20.1
  mockito: ^5.0.17
  file_testing: ^3.0.0
  

flutter_icons:
  image_path: "assets/images/logo-gomac.png"
  android: true # can specify file name here e.g. "ic_launcher"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-gomac.png
    - assets/images/logo-gomac-texto.png
    - assets/images/Posicion.jpeg
    - assets/sqljs/sql-wasm.js # este archivo tiene una modificacion: se cambia "sql-wasm.wasm" por "assets/assets/sqljs/sql-wasm.wasm"
    - assets/sqljs/sql-wasm.wasm 

