// Mocks generated by Mockito 5.0.15 from annotations
// in inspecciones/test/features/creacion_cuestionarios/creacion_controllers_test.dart.
// Do not manually edit this file.

import 'package:flutter/foundation.dart' as _i4;
import 'package:inspecciones/core/enums.dart' as _i7;
import 'package:inspecciones/features/creacion_cuestionarios/creacion_controls.dart'
    as _i5;
import 'package:inspecciones/infrastructure/moor_database.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:moor/moor.dart' as _i2;
import 'package:reactive_forms/reactive_forms.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeValue_0<T> extends _i1.Fake implements _i2.Value<T> {}

class _FakeFormControl_1<T> extends _i1.Fake implements _i3.FormControl<T> {}

class _FakeValueNotifier_2<T> extends _i1.Fake implements _i4.ValueNotifier<T> {
}

class _FakeFormGroup_3 extends _i1.Fake implements _i3.FormGroup {}

/// A class which mocks [CamposGeneralesPreguntaController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCamposGeneralesPreguntaController extends _i1.Mock
    implements _i5.CamposGeneralesPreguntaController {
  MockCamposGeneralesPreguntaController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get parteDeCuadricula =>
      (super.noSuchMethod(Invocation.getter(#parteDeCuadricula),
          returnValue: false) as bool);
  @override
  _i2.Value<String> get tituloInicial =>
      (super.noSuchMethod(Invocation.getter(#tituloInicial),
          returnValue: _FakeValue_0<String>()) as _i2.Value<String>);
  @override
  _i3.FormControl<String> get tituloControl => (super.noSuchMethod(
      Invocation.getter(#tituloControl),
      returnValue: _FakeFormControl_1<String>()) as _i3.FormControl<String>);
  @override
  _i2.Value<String> get descripcionInicial =>
      (super.noSuchMethod(Invocation.getter(#descripcionInicial),
          returnValue: _FakeValue_0<String>()) as _i2.Value<String>);
  @override
  _i3.FormControl<String> get descripcionControl => (super.noSuchMethod(
      Invocation.getter(#descripcionControl),
      returnValue: _FakeFormControl_1<String>()) as _i3.FormControl<String>);
  @override
  _i3.FormControl<_i6.Sistema?> get sistemaControl =>
      (super.noSuchMethod(Invocation.getter(#sistemaControl),
              returnValue: _FakeFormControl_1<_i6.Sistema?>())
          as _i3.FormControl<_i6.Sistema?>);
  @override
  _i4.ValueNotifier<List<_i6.SubSistema>> get subSistemasDisponibles =>
      (super.noSuchMethod(Invocation.getter(#subSistemasDisponibles),
              returnValue: _FakeValueNotifier_2<List<_i6.SubSistema>>())
          as _i4.ValueNotifier<List<_i6.SubSistema>>);
  @override
  _i3.FormControl<_i6.SubSistema?> get subSistemaControl =>
      (super.noSuchMethod(Invocation.getter(#subSistemaControl),
              returnValue: _FakeFormControl_1<_i6.SubSistema?>())
          as _i3.FormControl<_i6.SubSistema?>);
  @override
  _i2.Value<String?> get ejeInicial =>
      (super.noSuchMethod(Invocation.getter(#ejeInicial),
          returnValue: _FakeValue_0<String?>()) as _i2.Value<String?>);
  @override
  _i3.FormControl<String?> get ejeControl => (super.noSuchMethod(
      Invocation.getter(#ejeControl),
      returnValue: _FakeFormControl_1<String?>()) as _i3.FormControl<String?>);
  @override
  _i2.Value<String?> get ladoInicial =>
      (super.noSuchMethod(Invocation.getter(#ladoInicial),
          returnValue: _FakeValue_0<String?>()) as _i2.Value<String?>);
  @override
  _i3.FormControl<String?> get ladoControl => (super.noSuchMethod(
      Invocation.getter(#ladoControl),
      returnValue: _FakeFormControl_1<String?>()) as _i3.FormControl<String?>);
  @override
  _i2.Value<String?> get posicionZInicial =>
      (super.noSuchMethod(Invocation.getter(#posicionZInicial),
          returnValue: _FakeValue_0<String?>()) as _i2.Value<String?>);
  @override
  _i3.FormControl<String?> get posicionZControl => (super.noSuchMethod(
      Invocation.getter(#posicionZControl),
      returnValue: _FakeFormControl_1<String?>()) as _i3.FormControl<String?>);
  @override
  _i2.Value<_i7.TipoDePregunta> get tipoIncial =>
      (super.noSuchMethod(Invocation.getter(#tipoIncial),
              returnValue: _FakeValue_0<_i7.TipoDePregunta>())
          as _i2.Value<_i7.TipoDePregunta>);
  @override
  _i3.FormControl<_i7.TipoDePregunta> get tipoDePreguntaControl =>
      (super.noSuchMethod(Invocation.getter(#tipoDePreguntaControl),
              returnValue: _FakeFormControl_1<_i7.TipoDePregunta>())
          as _i3.FormControl<_i7.TipoDePregunta>);
  @override
  _i3.FormGroup get control => (super.noSuchMethod(Invocation.getter(#control),
      returnValue: _FakeFormGroup_3()) as _i3.FormGroup);
  @override
  String toString() => super.toString();
}
