# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ actualizacion_flutter ]
  pull_request:
    branches: [ actualizacion_flutter ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Update sqlite
      run: |
        sudo apt install unzip
        wget https://sqlite.org/2021/sqlite-tools-linux-x86-3360000.zip
        unzip sqlite-tools-linux-x86-3360000.zip
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
        sudo cp -a sqlite-tools-linux-x86-3360000/. /usr/local/bin
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.6'
        channel: 'beta'

    - name: Install dependencies
      run: flutter pub get

    - name: Check format
      run: flutter format --set-exit-if-changed .
      
    - name: Run build runner
      run: flutter pub run build_runner build
      
    # Consider passing '--fatal-infos' for slightly stricter analysis.
    - name: Analyze project source
      run: flutter analyze
      
    - name: Run tests
      run: |
        export PATH="$PATH:/usr/local/bin"
        flutter test --coverage

    - name: Upload coverage to Codecov 
      uses: codecov/codecov-action@v1 
      with: 
        token: ${{ secrets.CODECOV_TOKEN }} 
        file: coverage/lcov.info
